// https://www.w3schools.com/howto/howto_js_navbar_hide_scroll.asp

var prevScrollpos = window.pageYOffset;

window.onscroll = function() {
    var currentScrollPos = window.pageYOffset;

    // Navbar hide/show functionality
    var navbar = document.querySelector('.navbar');
    if (navbar) {
        if (prevScrollpos > currentScrollPos) {
            // Scrolling UP - show navbar
            navbar.style.transform = "translateY(0)";
        } else {
            // Scrolling DOWN - hide navbar
            navbar.style.transform = "translateY(-100%)";
        }
    }

    prevScrollpos = currentScrollPos;

    // Scroll to top button functionality
    scrollFunction();
};

// Get the button
let mybutton = document.getElementById("myBtn");

// When the user scrolls down 20px from the top of the document, show the button
function scrollFunction() {
    if (!mybutton) return;

    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        mybutton.style.display = "flex";
    } else {
        mybutton.style.display = "none";
    }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
    document.body.scrollTop = 0; // For Safari
    document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
}

// Flight Data Trial - JavaScript
// Aviationstack API Configuration
const API_KEY = '34f281d79e77f64b899e6d43183a8046';
const AIRPORT_CODE = 'ZQN';
const filterBtns = document.querySelectorAll('.filter-btn');
const cardCols = document.querySelectorAll('.card-col');
const emptyState = document.getElementById('empty-state');


// API KEY
function checkApiKey() {
    if (!API_KEY || API_KEY === 'your_api_key_here') {
        document.getElementById('api-warning').classList.remove('d-none');
        document.getElementById('api-loading').classList.add('d-none');
        return false;
    }
    return true;
}

// Setting times to local times. 

function updateLastUpdated() {
    const now = new Date();
    const timeString = now.toLocaleTimeString('en-NZ', {
        hour: '2-digit',
        minute: '2-digit'
    });
    document.getElementById('last-updated').textContent = timeString;
}

// Refresh button integration. 
document.getElementById('refresh-btn')?.addEventListener('click', function() {
    document.getElementById('api-content').classList.add('d-none');
    document.getElementById('api-loading').classList.remove('d-none');
    document.getElementById('api-error').classList.add('d-none');
    fetchLiveFlights();
});

if (checkApiKey()) {
    fetchLiveFlights();
}

// Harrison's Filter Code
// Same structure as the Visit page:
// 1. remove active class from all buttons
// 2. add active to the clicked button
// 3. compare selected category with each card's data-cat
// 4. toggle .hidden class
// 5. show empty state if nothing matches

filterBtns.forEach(btn => {
    btn.addEventListener('click', () => {

        // Remove active from all buttons, add to clicked one
        filterBtns.forEach(b => b.classList.remove('active'));
        btn.classList.add('active');

        const selectedCat = btn.dataset.cat;
        let visibleCount = 0;

        cardCols.forEach(col => {
            const matches = selectedCat === 'all' || col.dataset.cat === selectedCat;
            // Toggle the .hidden class — CSS handles the fade transition
            col.classList.toggle('hidden', !matches);
            if (matches) visibleCount++;
        });

        // Show empty state message if nothing matches
        emptyState.style.display = visibleCount === 0 ? 'block' : 'none';
    });
});


// ============================================
// CHATGPT-GENERATED CODE - Advanced API integration
// This code was generated by ChatGPT AI assistant
// to handle the complex Aviationstack API integration
// ============================================

/**
 * Fetch live arrivals from Aviationstack API
 * Generated by ChatGPT to handle API requests and error handling
 */
async function fetchLiveFlights() {
    const url = `https://api.aviationstack.com/v1/flights?arr_iata=${AIRPORT_CODE}&access_key=${API_KEY}&limit=10`;

    try {
        const response = await fetch(url);
        const data = await response.json();

        if (data.error) {
            throw new Error(data.error.message || 'API Error');
        }

        displayFlights(data.data || []);

    } catch (error) {
        console.error('API Error:', error);
        document.getElementById('api-loading').classList.add('d-none');
        document.getElementById('api-error').classList.remove('d-none');
        document.getElementById('error-text').textContent = error.message;
    }
}

/**
 * Display flights in the table
 * Generated by ChatGPT to populate HTML table with API data
 */
function displayFlights(flights) {
    // Hide loading, show content
    document.getElementById('api-loading').classList.add('d-none');
    document.getElementById('api-content').classList.remove('d-none');

    const tbody = document.getElementById('flights-body');

    // Check if we have flights
    if (!flights || flights.length === 0) {
        tbody.innerHTML = '<tr><td colspan="5" class="text-center text-muted">No flights currently available</td></tr>';
        return;
    }

    // Build table rows
    let html = '';
    for (let i = 0; i < flights.length; i++) {
        const flight = flights[i];

        // Get flight details
        const airline = flight.airline?.name || 'Unknown';
        const flightNum = getFlightNumber(flight);
        const from = flight.departure?.iata || 'N/A';
        const time = formatTime(flight.arrival?.scheduled);
        const status = formatStatus(flight.flight_status);
        const statusClass = getStatusClass(flight.flight_status);

        html += `
            <tr>
                <td><strong>${flightNum}</strong></td>
                <td>${airline}</td>
                <td>${from}</td>
                <td>${time}</td>
                <td><span class="badge ${statusClass}">${status}</span></td>
            </tr>
        `;
    }

    tbody.innerHTML = html;
    updateLastUpdated();
}

/**
 * Get flight number from flight object
 * Generated by ChatGPT to extract and format flight numbers
 */
function getFlightNumber(flight) {
    if (flight.flight?.iata) {
        return flight.flight.iata;
    }
    if (flight.airline?.iata_code && flight.flight?.number) {
        return flight.airline.iata_code + flight.flight.number;
    }
    return 'N/A';
}

/**
 * Format time for display (NZ time)
 * Generated by ChatGPT to convert UTC times to New Zealand timezone
 */
function formatTime(dateTimeString) {
    if (!dateTimeString) return '--';

    const date = new Date(dateTimeString);
    return date.toLocaleTimeString('en-NZ', {
        timeZone: 'Pacific/Auckland',
        hour: '2-digit',
        minute: '2-digit',
        hour12: true
    });
}

/**
 * Format status text
 * Generated by ChatGPT to capitalize status text
 */
function formatStatus(status) {
    if (!status) return 'Unknown';
    return status.charAt(0).toUpperCase() + status.slice(1).toLowerCase();
}

/**
 * Get CSS class for status badge
 * Generated by ChatGPT to map API status values to Bootstrap badge colors
 */
function getStatusClass(status) {
    const statusMap = {
        'active': 'bg-success',
        'scheduled': 'bg-primary',
        'landed': 'bg-info',
        'delayed': 'bg-warning',
        'cancelled': 'bg-danger',
        'en route': 'bg-secondary'
    };
    return statusMap[status?.toLowerCase()] || 'bg-secondary';
}