// https://www.w3schools.com/howto/howto_js_navbar_hide_scroll.asp

var prevScrollpos = window.pageYOffset;

window.onscroll = function() {
    var currentScrollPos = window.pageYOffset;

    // Navbar hide/show functionality
    var navbar = document.querySelector('.navbar');
    if (navbar) {
        if (prevScrollpos > currentScrollPos) {
            // Scrolling UP - show navbar
            navbar.style.transform = "translateY(0)";
        } else {
            // Scrolling DOWN - hide navbar
            navbar.style.transform = "translateY(-100%)";
        }
    }

    prevScrollpos = currentScrollPos;

    // Scroll to top button functionality
    scrollFunction();
};

// Get the button
let mybutton = document.getElementById("myBtn");

// When the user scrolls down 20px from the top of the document, show the button
function scrollFunction() {
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        mybutton.style.display = "block";
    } else {
        mybutton.style.display = "none";
    }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
    document.body.scrollTop = 0; // For Safari
    document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
}

// Card carousel responsive functionality

// The following code was generated by ChatGPT:
const wrapper = document.querySelector('#carouselExample .carousel-inner');
const allCards = document.querySelectorAll('#carouselExample .card-div');
const indicators = document.querySelector('#carouselExample .carousel-indicators');

function getCardsPerSlide() {
    if (window.innerWidth >= 1200) return 4;
    if (window.innerWidth >= 992) return 3;
    if (window.innerWidth >= 768) return 2;
    return 1;
}

function updateSlides() {
    const cardsPerSlide = getCardsPerSlide();
    const totalSlides = Math.ceil(allCards.length / cardsPerSlide);

    wrapper.innerHTML = '';

    for (let i = 0; i < totalSlides; i++) {
        const slide = document.createElement('div');
        slide.className = i === 0 ? 'carousel-item active' : 'carousel-item';

        const cardsWrapper = document.createElement('div');
        cardsWrapper.className = 'cards-wrapper';

        const startIndex = i * cardsPerSlide;
        const endIndex = Math.min(startIndex + cardsPerSlide, allCards.length);

        for (let j = startIndex; j < endIndex; j++) {
            cardsWrapper.appendChild(allCards[j].cloneNode(true));
        }

        slide.appendChild(cardsWrapper);
        wrapper.appendChild(slide);
    }

    indicators.innerHTML = '';
    for (let i = 0; i < totalSlides; i++) {
        const btn = document.createElement('button');
        btn.type = 'button';
        btn.setAttribute('data-bs-target', '#carouselExample');
        btn.setAttribute('data-bs-slide-to', i);
        if (i === 0) {
            btn.className = 'active';
            btn.setAttribute('aria-current', 'true');
        }
        indicators.appendChild(btn);
    }
}

updateSlides();
window.addEventListener('resize', updateSlides);
